name: hurricane-env
channels:
  - defaults
  - conda-forge
dependencies:
  - attrs=25.3.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cffi=1.17.1
  - cfgrib=0.9.15.0
  - click=8.2.1
  - eccodes=2.38.3
  - expat=2.7.1
  - findlibs=0.1.2
  - hdf4=4.2.15
  - hdf5=1.14.4
  - jasper=4.2.8
  - krb5=1.21.3
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.50
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libxml2=2.13.5
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - ncurses=6.4
  - numpy=2.1.2
  - openssl=3.5.2
  - packaging=25.0
  - pandas=2.2.3
  - pip=25.1
  - pycparser=2.22
  - python=3.11.8
  - python-dateutil=2.9.0.post0
  - python-eccodes=2.37.0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2024.1
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.2
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - xarray=2025.7.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.10.0
      - fastapi==0.116.1
      - idna==3.10
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.42
      - starlette==0.47.2
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1